### ISSUE TITLE
Suggested Wording Change for Problem 2

### ISSUE THREAD

**Issue by jlaw8504** [Jessime/Excision#1]
Write a program that takes an empty folder location as input. This folder will have multiple subfolders, each of which has a unknown name and contains two .csv files from one of your agents. **The .csv files contains the temperatures of a specific rooms within the factory, each agent took the same path within the factory so the indexes of the temperatures within the .csv files represent the same rooms. In other words, each .csv file is a technical replicate of the "heatmap" of the factory.** Your program should collect all of these .csv files and use them to find the index, **meaning the room,** and temperature of the **consistently** hottest location in the Theraptrix factory. **Specifically, write** both the index and the average **room** temperature (**average across all the replicates** rounded to the nearest integer) to results/2.txt.

**Comment by Jessime** [comment]
I've tweaked the wording; I think it's quite a bit clearer now. What do you think?

Here's the commit:
https://github.com/Jessime/Excision/commit/c625d2ce51ef4fcfbb91508dcf39569e992f9a5f

**Comment by jlaw8504** [comment]
Much clearer now.  Thanks!
