### ISSUE TITLE
Cannot run ExcisionApp.py

### ISSUE THREAD

**Issue by rmeganck1** [Jessime/Excision#12]
I just installed the bash on Ubuntu on Windows shell, and tried to use it to open the app. I got the following error: 

File "ExcisionApp.py", line 14, in <module>
      from flask import Flask, render_template, redirect, request, jsonify
ModuleNotFoundError: No module named 'flask'

Then I tried to run it from Windows command prompt, as I have been doing all along. Then I got the following error:

File "ExcisionApp.py", line 17, in <module>
       from play_levels import State
File "C:\Users\Rita\Documents\GitHub\Excision\src\play_levels.py", line 17, in <module>
      class State():
  File "C\Users\Rita\Documents\GitHub\Excision\src\play_levels.py", line 69, in State
      lvl_data=load(open('levels.pkl', 'rb'))
ModuleNotFoundError: No module named 'pandas.core.indexes'

**Comment by Jessime** [comment]
> Ubuntu for Windows

The app hasn't been tested on this platform at all. I would be surprised if you could get this to work, and wouldn't recommend spending the time to figure it out (unless you're ready to make a project out of the endeavor). 

> Windows

At the command line, do:

```bash
conda upgrade --all
```

You need a slightly newer version of `pandas`.

**Comment by rmeganck1** [comment]
Thanks, the Windows is working again now. By the way, I was able to get the code to execute on Ubuntu for Windows, but the app won't accept answers.
