### ISSUE TITLE
Level 5 not accessible

### ISSUE THREAD

**Issue by maerniel** [Jessime/Excision#15]
When I try to access level 5, I receive a server error. The address is:
http://127.0.0.1:5000/play/CAPTURE

The error is:
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by Jessime** [comment]
What does the error in your terminal say?

**Comment by maerniel** [comment]
ValueError: 'CAPTURE' is not in list
