### ISSUE TITLE
Tutorial: running .py files on windows

### ISSUE THREAD

**Issue by maerniel** [Jessime/Excision#3]
Catching up on the first assignment, during the tutorial I've been simply trying to make sure I can run a python file (.py) in the windows command line, but having no luck. Is there something I need to set up to be able to do this? Currently windows has no association with .py extension. (I'll admit my previous experience is pretty much purely running python through ipython notebook).

**Comment by maerniel** [comment]
I've gotten it to the point where 'gc_calc.py' will run; however, './gc_calc.py' will not and regardless it doesn't seem to be taking command line input (the sequence) unless I run it using the python command. this means that submitting the file to excision doesn't register as a correct response.

**Comment by lafosse** [comment]
Are you using Windows Command Prompt? Also, what does the console state if you try to run your file and it fails?

**Comment by maerniel** [comment]
Yes, I'm using windows command prompt.
In my program I'm using sys.argv
If I use 'gc_calc.py ATATGCGC' it only reads the file path as input (I've checked this by printing sys.argv). So I get IndexError: list index out of range. I can remove the error itself by rewriting the code to index 0, but then I'm getting the GC content of the file path.
I can now get '.\gc_calc.py' running (that was simply having / instead of \), but I get the same error.

**Comment by maerniel** [comment]
My current code (works for 'python gc_calc.py GAGATCTC' not for '.\gc_calc.py GAGATCTC'):

import sys

sequence=sys.argv[1]

GC=(sequence.count('G')+sequence.count('C'))/len(sequence)

f=open("D:/Documents/GitHub/Excision/results/tutorial/gc.txt",'w')
f.write(str(int(round(GC,2)*100))+"%")
f.close()

**Comment by maerniel** [comment]
And I've found a way to get it to run in Windows command line. I had to update my registry (see answer 3 in the link: https://stackoverflow.com/questions/9880540/python-command-line-arguments-windows); however, that doesn't make it work when I submit it to Excision itself.

**Comment by lafosse** [comment]
Does that code snippet work when you submit through Excision? If not, what is the error displayed?

**Comment by maerniel** [comment]
It runs, but is classified as wrong, with output:

Your answer is not correct.

Could it simply be an issue with the file path not working where the program is running? In that case how would I specify the path in an appropriate fashion to work on both my computer and with Excision?

**Comment by lafosse** [comment]
It seems like the script you've put up here should work. What are the contents of `gc.txt`?

**Comment by maerniel** [comment]
I'm getting:
43%

What string is being analysed? What should the answer be? Does Excision just run the file where it is on my computer?

**Comment by lafosse** [comment]
Turns out you're doing it correctly! The answer that you're "supposed" to get is 42% (because we just used `int(` instead of `int(round(`. 

We actually just fixed this same problem in one of the levels, but forgot to go back and fix it in the tutorial. Thanks for catching this mistake. We'll take care of it ASAP!

**Comment by maerniel** [comment]
Ah. Thanks for letting me know, and glad to learn I've gotten things working eventually.
